# Generated by Django 4.1.5 on 2023-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCatPuestosPrueba',
            fields=[
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('id_puesto', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('fecha_baja', models.DateField(default='1900-01-01')),
                ('empleado_registra', models.IntegerField()),
                ('empleado_baja', models.IntegerField(default='')),
            ],
        ),
    ]
