# Generated by Django 4.1.5 on 2023-01-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcatpuestosprueba',
            name='empleado_baja',
            field=models.IntegerField(blank=True),
        ),
    ]
